# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='MyBio',
        ),
    ]
