# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160621_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='MyBio',
        ),
    ]
